inside_lights_automations:
  name: Inside Lights Without Stefan
  entities:
    - light.bedroom_ceiling_light
    - light.bedside_lamp
    - light.living_room_ceiling_light_level
    - light.living_room_spotlights_level
    - light.passage_ceiling_spotlights_level
    - light.upstairs_hallway_ceiling_light_level
    - light.dining_area_ceiling_light_level
    - light.isa_ceiling_light
    - light.e14
    - light.floorlamp_uplight
    - light.gateway_light_34ce008bfc4b